language: ruby
cache:
  bundler: true
  directories:
  - node_modules
  - $HOME/bin
before_install:
  - nvm install node
  - ci/install_deps.sh
  - export PATH=$PATH:$HOME/bin/:$(npm bin)
before_script:
  - bin/rake acceptance_test
script:
  - bin/rake build
env:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES: 1
