language: ruby
cache:
  bundler: true
  directories:
  - node_modules
  - "$HOME/bin"
before_install:
- gem update --system
- gem install bundler
- nvm install node
- ci/install_deps.sh
- export PATH=$PATH:$HOME/bin/:$(npm bin)
script:
- bin/rake s3_sync
env:
  matrix:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES: 1
  global:
    secure: LRQJ8AOZjxmxBicN+YL73DcIn6pAgGkS+fRQmeV1M2hc907G59Jo/sQU8EUlJzeOn8HbqlfW8hCJoDiJXmYgbxsbzfPW9LnFLqi8/CL+brYpB17Y9NX3/ETFJ8jONo9f+Qkrj+BDiBC1whXSU7fKjX0y3LfjOjdGte4p323SsMVEqBOpZQec2szh+uEPUfoUNdmwacML/ub5hHZHq3nlAcjjvxvszqHM85npeGga4eaG4eYCLZlVkp4/Wi/iUJ3+XwBDYVNIZGQFsansgBy7LhZpidUAdWiLY8Mji+zGKsL2pys0DKIzA9/5B7Sv5sowdzNY/dv/2uaCvgXSEoGnW/8bdT30KpeM/EPavQULxqGvL1ZEBuJZH5o1gyUVYQrT0aCDvibx3lSONvZFvc9c4DlN9Rz/3vmNyVOimvFyRxbviijbOx3CEr/hajpfyejfrV2j1NGUp5xvA0arb5hWZIWF1hlydF5poek/GeeFJBEY7OCg7iDhmW+zDZKqSJyPr16LswmuTe3L1CMI4+ogIZUGS2kirB0Je3eEw0/v1VkkO86HndmQx2IffB6yPLrrn2i1JYMzngWaF9HiTdOA0zrtG6Dep+EWl4h0AvEGBJ4+GwPrqwJ4m09nn/jlP0FGGoOMkZmhuFI7RGhndzdxqZe+1ATtlERxpNYYrItm5o0=
