language: ruby
bundler_args: --without test development
cache:
  bundler: true
  directories:
  - node_modules
  - $HOME/bin
before_install:
  - gem update --system
  - gem update
  - nvm install node
  - ci/install_deps.sh
  - export PATH=$PATH:$HOME/bin/:$(npm bin)
script:
  - bin/rake acceptance_test
  - bin/rake build
env:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES: 1
