language: ruby
bundler_args: --without test development
cache:
  bundler: true
  directories:
  - node_modules
  - $HOME/bin
before_install:
  - nvm install node
  - ci/install_deps.sh
  - export PATH=$PATH:$HOME/bin/:$(npm bin)
script:
  - bundle exec middleman build -e production
notifications:
  email: false
